apiVersion: apps/v1
kind: Deployment
metadata:
  name: namegen-app
  labels:
    app: namegen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: namegen
  template:
    metadata:
      labels:
        app: namegen
    spec:
      containers:
      - name: namegen
        image: public.ecr.aws/k5u0o7b3/moaad-namegen:latest
        ports:
        - containerPort: 8080
        env:
          - name: MONGODB_URL
            #value: mongodb://genuser:password@mongo:27017/namegen
            value: "mongodb://genuser:password@mongo.default.svc.cluster.local:27017/namegen"